---
name: ci 
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
      - mkdocs.yml
      - 'docs/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: sudo apt-get install -y pngquant
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install pillow cairosvg
      - run: pip install material-plausible-plugin
      - run: mkdocs gh-deploy --force
